---
- name: Install the NetworkManager
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - networkmanager
    - network-manager-applet
    - networkmanager-openvpn
  tags:
    - networkmanager
